// <auto-generated />
using System;
using BankAppCore.Data.EFContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankAppCore.Migrations
{
    [DbContext(typeof(EFContext.ShopContext))]
    [Migration("20190330160501_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankApp.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("ClientSocialSecurityNumber");

                    b.Property<DateTime>("CreationDate");

                    b.Property<short>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ClientSocialSecurityNumber");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankApp.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("ClientSocialSecurityNumber")
                        .IsRequired();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("SecretNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("ClientSocialSecurityNumber");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("BankApp.Models.Client", b =>
                {
                    b.Property<string>("SocialSecurityNumber")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(13);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("IdentityCardNumber")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("SocialSecurityNumber");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BankApp.Models.UserActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(300);

                    b.HasKey("Id");

                    b.ToTable("UserActionLogs");
                });

            modelBuilder.Entity("BankApp.Models.Account", b =>
                {
                    b.HasOne("BankApp.Models.Client", "Client")
                        .WithMany("Accounts")
                        .HasForeignKey("ClientSocialSecurityNumber");
                });

            modelBuilder.Entity("BankApp.Models.Bill", b =>
                {
                    b.HasOne("BankApp.Models.Client", "Client")
                        .WithMany("Bills")
                        .HasForeignKey("ClientSocialSecurityNumber")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
